### ISSUE TITLE
Color code mismatch in graph and stats

### ISSUE THREAD

**Issue by alphasingh** [ChiragSaini/Covid19-Dashboard#5]
After #4 there is a mismatch in colors being represented in the graph and the ones being used in the country stats in the card views. 
@fs0sp I can understand that red makes more sense for "dead" but can we change the graph colors accordingly?
@ChiragSaini I could not see any settings for graph colors in the code, so matched it with the card colors instead. If we can make them both represent same attributes with the same colors, it would be better I think.

**Comment by ChiragSaini** [comment]
This issue has been fixed. Now both chart colors and bar colors match.

**Comment by alphasingh** [comment]
Closing this as resolved now.
